name = "jordanhayes.dev"
compatibility_date = "2025-11-21"

# If you're building a Pages Functions project, remove "main" and add:
pages_build_output_dir = "./dist"

[vars]
# Add any environment variables you need here

[[d1_databases]]
binding = "DB"              # This is the name you'll use in your Worker (env.DB)
database_name = "contacts-db"
database_id = "ddbe3b15-4dbb-4b8a-ba6a-c3c610c3b9f1"

# Optional: separate production database (recommended)
# [[d1_databases]]
# binding = "DB"
# database_name = "contacts-db"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
# preview_database_id = "contacts-db"

